//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muay_tahi_administrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public int Id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public Nullable<double> pago { get; set; }
        public System.DateTime fechaPago { get; set; }
        public Nullable<bool> habilitado { get; set; }
        public Nullable<double> debe { get; set; }
    }
}
